import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AcceptedByCategory } from '../components/AcceptedByCategory'
import { HighlightedText } from '../components/HighlightedText'
import { SummaryCards } from '../components/SummaryCards'
import type { AnalysisResult, CategoryColorMap, Highlight, TraceStep } from '../types'

type Props = {
  result: AnalysisResult | null
  colors: CategoryColorMap
}

export function ResultsPage({ result, colors }: Props) {
  const categories = Object.keys(colors)
  const [selected, setSelected] = useState<Highlight | null>(null)
  const [traceOpen, setTraceOpen] = useState(false)

  const effectiveSelected = useMemo(() => {
    if (!result) return null
    if (selected) return selected
    return result.highlights?.[0] ?? null
  }, [result, selected])

  const traceSteps: TraceStep[] = effectiveSelected?.trace ?? []

  useEffect(() => {
    if (!traceOpen) return
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') setTraceOpen(false)
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [traceOpen])

  return (
    <div className="app">
      <main className="grid">
        <div className="pageTitleRow card--span2">
          <Link className="btn btn--secondary pageTitleRow__back" to="/">
            <span className="btnIcon" aria-hidden="true">←</span>
            <span>Back to input</span>
          </Link>
          <div className="pageTitle pageTitleRow__title">
            <div className="pageTitle__headline">Results</div>
            <div className="pageTitle__sub">Summary report generated by the DFA.</div>
          </div>
          <div className="pageTitleRow__spacer" />
        </div>

        <section className="card card--span2">
          <h2 className="card__title">Summary</h2>
          {result ? (
            <SummaryCards
              totalTokens={result.totalTokens}
              acceptedTokens={result.acceptedTokens}
              categoryTokenCounts={result.categoryTokenCounts}
              colors={colors}
            />
          ) : (
            <div className="empty">
              No results loaded. Go back to the input page and click <b>Analyze</b>.
            </div>
          )}
        </section>

        <section className="card card--span2">
          <h2 className="card__title">Accepted Words by Category</h2>
          {result ? (
            <AcceptedByCategory acceptedByCategory={result.acceptedByCategory} colors={colors} />
          ) : (
            <div className="empty">No results yet.</div>
          )}
        </section>

        <section className="card card--span2">
          <h2 className="card__title">Highlighted text</h2>
          {result ? (
            <>
              <HighlightedText
                text={result.text}
                highlights={result.highlights}
                colors={colors}
                selected={effectiveSelected}
                onSelectHighlight={(h) => {
                  setSelected(h)
                  setTraceOpen(true)
                }}
              />
              <div className="legend legend--inline">
                <div className="legend__title">Legend</div>
                <div className="legendGrid">
                  {categories.map((c) => (
                    <div key={c} className="legendItem">
                      <span className="swatch" style={{ background: colors[c] }} />
                      <span className="legendName">{c}</span>
                      <span className="legendCount">{result.categoryTokenCounts?.[c] ?? 0}</span>
                    </div>
                  ))}
                </div>
                <div className="muted">Multi-category words are shown with a combined (gradient) highlight.</div>
              </div>
            </>
          ) : (
            <div className="empty">No results yet.</div>
          )}
        </section>
      </main>

      {result && effectiveSelected && traceOpen ? (
        <div
          className="modalOverlay"
          role="presentation"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setTraceOpen(false)
          }}
        >
          <div className="modal" role="dialog" aria-modal="true" aria-label="DFA trace details">
            <div className="modalHeader">
              <div>
                <div className="modalTitle">DFA Trace</div>
                <div className="modalSub muted">Press Esc or click outside to close.</div>
              </div>
              <button type="button" className="btn btn--secondary" onClick={() => setTraceOpen(false)}>
                Close
              </button>
            </div>

            <div className="traceMeta">
              <span className="pill">
                <span className="muted">Token</span>
                <span className="mono">
                  {effectiveSelected.original} ({effectiveSelected.lower})
                </span>
              </span>
              <span className="pill">
                <span className="muted">Position</span>
                <span className="mono">
                  {effectiveSelected.start}–{effectiveSelected.end - 1}
                </span>
              </span>
              <span className="pill">
                <span className="muted">Categories</span>
                <span>{(effectiveSelected.categories ?? []).join(', ')}</span>
              </span>
              <span className="pill">
                <span className="muted">Steps</span>
                <span className="mono">{traceSteps.length}</span>
              </span>
            </div>

            {traceSteps.length === 0 ? (
              <div className="empty">No trace available for this token.</div>
            ) : (
              <div className="traceTable" role="table" aria-label="DFA trace table">
                <div className="traceTable__head" role="row">
                  <div role="columnheader">Step</div>
                  <div role="columnheader">Char</div>
                  <div role="columnheader">From</div>
                  <div role="columnheader">To</div>
                  <div role="columnheader">Note</div>
                </div>
                {traceSteps.map((s, idx) => {
                  const fromLbl = `q${s.from}`
                  const toLbl = s.trap ? 'TRAP' : `q${s.to}`
                  const note = s.trap ? 'Entering trap state — processing terminated' : ''
                  return (
                    <div key={`${idx}:${s.ch}:${s.from}:${s.to}`} className="traceTable__row" role="row">
                      <div className="mono" role="cell">
                        {idx + 1}
                      </div>
                      <div className="mono" role="cell">
                        '{s.ch}'
                      </div>
                      <div className="mono" role="cell">
                        {fromLbl}
                      </div>
                      <div className="mono" role="cell">
                        {toLbl}
                      </div>
                      <div className={s.trap ? 'traceNote traceNote--trap' : 'traceNote'} role="cell">
                        {note || '—'}
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  )
}

