import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AcceptedByCategory } from '../components/AcceptedByCategory'
import { HighlightedText } from '../components/HighlightedText'
import { SummaryCards } from '../components/SummaryCards'
import { TraceGraphviz } from '../components/TraceGraphviz'
import { TraceSubgraph } from '../components/TraceSubgraph'
import type { AnalysisResult, CategoryColorMap, SelectedToken, TraceStep } from '../types'

type Props = {
  result: AnalysisResult | null
  colors: CategoryColorMap
}

const API_BASE = 'http://127.0.0.1:8000'

export function ResultsPage({ result, colors }: Props) {
  const categories = Object.keys(colors)
  const [selected, setSelected] = useState<SelectedToken | null>(null)
  const [traceOpen, setTraceOpen] = useState(false)
  const [traceView, setTraceView] = useState<'graph' | 'subgraph'>('subgraph')

  const effectiveSelected = useMemo(() => {
    if (!result) return null
    if (selected) return selected
    const h = result.highlights?.[0]
    if (!h) return null
    return {
      original: h.original,
      lower: h.lower,
      start: h.start,
      end: h.end,
      categories: h.categories ?? [],
      accepted: true,
      trace: h.trace ?? [],
    }
  }, [result, selected])

  const traceSteps: TraceStep[] = effectiveSelected?.trace ?? []

  useEffect(() => {
    if (!traceOpen) return
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') setTraceOpen(false)
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [traceOpen])

  return (
    <div className="app">
      <main className="grid">
        <div className="pageTitleRow card--span2">
          <Link className="btn btn--secondary pageTitleRow__back" to="/">
            <span className="btnIcon" aria-hidden="true">←</span>
            <span>Back to input</span>
          </Link>
          <div className="pageTitle pageTitleRow__title">
            <div className="pageTitle__headline">Results</div>
            <div className="pageTitle__sub">Summary report generated by the DFA.</div>
          </div>
          <div className="pageTitleRow__spacer" />
        </div>

        <section className="card card--span2">
          <h2 className="card__title">Summary</h2>
          {result ? (
            <SummaryCards
              totalTokens={result.totalTokens}
              acceptedTokens={result.acceptedTokens}
              categoryTokenCounts={result.categoryTokenCounts}
              colors={colors}
            />
          ) : (
            <div className="empty">
              No results loaded. Go back to the input page and click <b>Analyze</b>.
            </div>
          )}
        </section>

        <section className="card card--span2">
          <h2 className="card__title">Accepted Words by Category</h2>
          {result ? (
            <AcceptedByCategory acceptedByCategory={result.acceptedByCategory} colors={colors} />
          ) : (
            <div className="empty">No results yet.</div>
          )}
        </section>

        <section className="card card--span2">
          <h2 className="card__title">Highlighted text</h2>
          {result ? (
            <>
              <HighlightedText
                text={result.text}
                highlights={result.highlights}
                colors={colors}
                selected={effectiveSelected}
                onSelectToken={async (t) => {
                  // If the clicked token is already an accepted highlight, we already have trace.
                  if (t.highlight) {
                    setSelected({
                      original: t.highlight.original,
                      lower: t.highlight.lower,
                      start: t.highlight.start,
                      end: t.highlight.end,
                      categories: t.highlight.categories ?? [],
                      accepted: true,
                      trace: t.highlight.trace ?? [],
                    })
                    setTraceOpen(true)
                    return
                  }

                  // Otherwise, fetch a DFA trace for this word from the API.
                  try {
                    const res = await fetch(`${API_BASE}/trace?word=${encodeURIComponent(t.lower)}`)
                    if (!res.ok) throw new Error(`Trace request failed: ${res.status}`)
                    const payload = (await res.json()) as {
                      original: string
                      lower: string
                      accepted: boolean
                      categories: string[]
                      trace: TraceStep[]
                    }
                    setSelected({
                      original: t.original,
                      lower: payload.lower,
                      start: t.start,
                      end: t.end,
                      categories: payload.categories ?? [],
                      accepted: Boolean(payload.accepted),
                      trace: payload.trace ?? [],
                    })
                    setTraceOpen(true)
                  } catch {
                    setSelected({
                      original: t.original,
                      lower: t.lower,
                      start: t.start,
                      end: t.end,
                      categories: [],
                      accepted: false,
                      trace: [],
                    })
                    setTraceOpen(true)
                  }
                }}
              />
              <div className="legend legend--inline">
                <div className="legend__title">Legend</div>
                <div className="legendGrid">
                  {categories.map((c) => (
                    <div key={c} className="legendItem">
                      <span className="swatch" style={{ background: colors[c] }} />
                      <span className="legendName">{c}</span>
                      <span className="legendCount">{result.categoryTokenCounts?.[c] ?? 0}</span>
                    </div>
                  ))}
                </div>
                <div className="muted">Multi-category words are shown with a combined (gradient) highlight.</div>
              </div>
            </>
          ) : (
            <div className="empty">No results yet.</div>
          )}
        </section>
      </main>

      {result && effectiveSelected && traceOpen ? (
        <div
          className="modalOverlay"
          role="presentation"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setTraceOpen(false)
          }}
        >
          <div className="modal modal--fullDFA" role="dialog" aria-modal="true" aria-label="DFA trace details">
            <div className="modalHeader">
              <div>
                <div className="modalTitle">DFA Trace</div>
                <div className="modalSub muted">Press Esc or click outside to close.</div>
              </div>
              <button type="button" className="btn btn--secondary" onClick={() => setTraceOpen(false)}>
                Close
              </button>
            </div>

            <div className="traceMeta">
              <span className="pill">
                <span className="muted">Token</span>
                <span className="mono">
                  {effectiveSelected.original} ({effectiveSelected.lower})
                </span>
              </span>
              <span className="pill">
                <span className="muted">Position</span>
                <span className="mono">
                  {effectiveSelected.start}–{effectiveSelected.end - 1}
                </span>
              </span>
              <span className="pill">
                <span className="muted">Categories</span>
                <span>{(effectiveSelected.categories ?? []).length ? (effectiveSelected.categories ?? []).join(', ') : '—'}</span>
              </span>
              <span className="pill">
                <span className="muted">Steps</span>
                <span className="mono">{traceSteps.length}</span>
              </span>
            </div>

            {traceSteps.length === 0 ? (
              <div className="empty">No trace available for this token.</div>
            ) : (
              <div className='traceTabBody traceTabBody--full'>
                <div className="traceTabs">
                  <button
                    type="button"
                    className={`traceTab${traceView === 'subgraph' ? ' traceTab--active' : ''}`}
                    onClick={() => setTraceView('subgraph')}
                  >
                    Full DFA
                  </button>
                  <button
                    type="button"
                    className={`traceTab${traceView === 'graph' ? ' traceTab--active' : ''}`}
                    onClick={() => setTraceView('graph')}
                  >
                    Graph
                  </button>
                </div>

                {traceView === 'subgraph' ? (
                  <TraceSubgraph
                    key={effectiveSelected?.lower}
                    word={effectiveSelected?.lower ?? ''}
                  />
                ) : (
                  <>
                    <div className="traceGraphWrap">
                      <div className="traceGraphHeader">
                        <div className="traceGraphTitle">Per-token subgraph</div>
                        <div className="muted">Edges are taken directly from the trace below.</div>
                      </div>
                      <TraceGraphviz traceSteps={traceSteps} accepted={effectiveSelected?.accepted ?? false} />
                      <div className="traceLegend">
                        <span className="legendPill legendPill--blue">Transition</span>
                        <span className="legendPill legendPill--green">Visited state</span>
                        <span className="legendPill legendPill--red">TRAP</span>
                      </div>
                    </div>

                    <div className="traceTable" role="table" aria-label="DFA trace table">
                      <div className="traceTable__head" role="row">
                        <div role="columnheader">Step</div>
                        <div role="columnheader">Char</div>
                        <div role="columnheader">From</div>
                        <div role="columnheader">To</div>
                        <div role="columnheader">Note</div>
                      </div>
                      {traceSteps.map((s, idx) => {
                        const fromLbl = `q${s.from}`
                        const toLbl = s.trap ? 'TRAP' : `q${s.to}`
                        const note = s.trap ? 'Entering trap state — processing terminated' : ''
                        return (
                          <div key={`${idx}:${s.ch}:${s.from}:${s.to}`} className="traceTable__row" role="row">
                            <div className="mono" role="cell">{idx + 1}</div>
                            <div className="mono" role="cell">'{s.ch}'</div>
                            <div className="mono" role="cell">{fromLbl}</div>
                            <div className="mono" role="cell">{toLbl}</div>
                            <div className={s.trap ? 'traceNote traceNote--trap' : 'traceNote'} role="cell">
                              {note || '—'}
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </>
                )}
              </div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  )
}

